from __future__ import annotations

import asyncio
import logging

from codehephaestus.config import Settings
from codehephaestus.git.worktree import (
    cleanup_worktree,
    ensure_worktree,
    get_current_sha,
    update_main,
)
from codehephaestus.github.client import GitHubClient
from codehephaestus.prd.generator import generate_prd
from codehephaestus.prd.models import PRDContext
from codehephaestus.priorities import PriorityDispatcher, Tier, WorkItem
from codehephaestus.ralph.runner import run_ralph
from codehephaestus.trackers.base import TaskTracker
from codehephaestus.utils.loop_prevention import LoopPrevention

log = logging.getLogger("codehephaestus.loop")


async def boot(settings: Settings, tracker: TaskTracker, github: GitHubClient) -> None:
    log.info("Validating Jira connection to %s...", settings.tracker_base_url)
    await tracker.validate_connection()

    username = await github.validate_auth()
    log.info("gh CLI authenticated as @%s", username)


async def _handle_work_item(
    work: WorkItem,
    *,
    settings: Settings,
    tracker: TaskTracker,
    github: GitHubClient,
    loop_prevention: LoopPrevention,
) -> None:
    issue = work.issue
    branch = tracker.get_issue_branch_name(issue)
    repo_path = settings.target_repo_path

    loop_prevention.record_attempt(issue.key)
    loop_prevention.mark_feedback_processed(issue.key)

    if work.tier == Tier.NEW_ISSUE and not settings.dry_run:
        log.info("%s: transitioning To Do → In Progress", issue.key)
        await tracker.transition_issue(issue.key, settings.jira_status_in_progress)
    elif work.tier == Tier.NEW_ISSUE:
        log.info("[DRY RUN] Would transition %s To Do → In Progress", issue.key)

    if settings.dry_run:
        log.info("[DRY RUN] Would create worktree for branch %s", branch)
        working_dir = repo_path
    else:
        working_dir = await ensure_worktree(branch, repo_path)

    # Build PRD context based on tier
    if work.tier == Tier.NEW_ISSUE:
        ctx = PRDContext(
            issue_key=issue.key,
            title=issue.title,
            description=issue.description,
        )
    elif work.tier == Tier.REVIEW_FEEDBACK:
        ctx = PRDContext(
            issue_key=issue.key,
            title=issue.title,
            description=issue.description,
            comments=work.context["comments"],
        )
    elif work.tier == Tier.CI_FAILURE:
        ctx = PRDContext(
            issue_key=issue.key,
            title=issue.title,
            description=issue.description,
            check_output=work.context.get("check_output", ""),
        )
    else:
        log.error("Unknown tier: %s", work.tier)
        return

    # Generate PRD → prd.json via AI tool (two-step)
    prd_path = await generate_prd(
        ctx,
        working_dir=working_dir,
        branch_name=branch,
        tool=settings.tool,
        dry_run=settings.dry_run,
    )

    # Run ralph loop to implement the PRD
    exit_code = await run_ralph(
        prd_path=prd_path,
        working_dir=working_dir,
        tool=settings.tool,
        max_iterations=settings.ralph_max_iterations,
        dry_run=settings.dry_run,
    )

    if exit_code > 1:
        log.warning("%s: ralph failed (exit=%d), skipping push", issue.key, exit_code)
        return

    if exit_code == 1:
        log.info("%s: ralph hit max iterations but may have partial work", issue.key)

    if settings.dry_run:
        log.info("[DRY RUN] Would push branch %s and manage PR", branch)
        return

    # Push
    await github.push_branch(branch)

    # Create PR if new issue
    pr_number = await github.find_pr_for_branch(branch)
    if work.tier == Tier.NEW_ISSUE and not pr_number:
        await github.create_pr(
            title=f"{issue.key}: {issue.title}",
            body=f"Implements {issue.key}\n\nGenerated by CodeHephaestus.",
            branch=branch,
            draft=True,
        )

    # CI status will be checked by check_ci_passed() housekeeping on next iteration

    sha_after = await get_current_sha(working_dir)
    loop_prevention.mark_sha_processed(sha_after)

    # Clean up worktree now that work is pushed
    await cleanup_worktree(branch, repo_path)


async def run_loop(settings: Settings) -> None:
    from codehephaestus.trackers import create_tracker

    tracker = create_tracker(settings)
    github = GitHubClient(settings.target_repo_path)
    loop_prevention = LoopPrevention()
    dispatcher = PriorityDispatcher(tracker, github, settings, loop_prevention)

    await boot(settings, tracker, github)

    iteration = 0
    mode = "infinite mode" if settings.max_iterations == 0 else f"max {settings.max_iterations}"

    while settings.max_iterations == 0 or iteration < settings.max_iterations:
        iteration += 1
        log.info("=== Iteration %d (%s) ===", iteration, mode)

        # Keep main up to date so new branches start from latest
        await update_main(settings.target_repo_path)

        # Housekeeping
        await dispatcher.check_merged_prs()
        await dispatcher.check_ci_passed()

        # Find next work item
        work = await dispatcher.find_next_work_item()

        if work:
            await _handle_work_item(
                work,
                settings=settings,
                tracker=tracker,
                github=github,
                loop_prevention=loop_prevention,
            )
        else:
            log.info("No work found.")

        if settings.max_iterations != 0 and iteration >= settings.max_iterations:
            break

        log.info("Iteration %d complete. Sleeping %ds...", iteration, settings.poll_interval)
        await asyncio.sleep(settings.poll_interval)

    log.info("Loop finished after %d iterations.", iteration)

    if hasattr(tracker, "close"):
        await tracker.close()
