from __future__ import annotations

import asyncio
import logging
from pathlib import Path

from codehephaestus.config import Settings
from codehephaestus.git.worktree import (
    cleanup_worktree,
    ensure_worktree,
    get_current_sha,
    update_main,
)
from codehephaestus.github.client import GitHubClient
from codehephaestus.priorities import PriorityDispatcher, Tier, WorkItem
from codehephaestus.trackers.base import TaskTracker
from codehephaestus.utils.loop_prevention import LoopPrevention
from codehephaestus.worker import render_prompt, run_tool

log = logging.getLogger("codehephaestus.loop")


async def boot(settings: Settings, tracker: TaskTracker, github: GitHubClient) -> None:
    log.info("Validating Jira connection to %s...", settings.tracker_base_url)
    await tracker.validate_connection()

    username = await github.validate_auth()
    log.info("gh CLI authenticated as @%s", username)


async def _handle_new_issue(
    work: WorkItem,
    *,
    settings: Settings,
    tracker: TaskTracker,
    github: GitHubClient,
    loop_prevention: LoopPrevention,
) -> None:
    """Handle a To Do ticket: plan, implement, post plan as Jira comment, create PR."""
    issue = work.issue
    branch = tracker.get_issue_branch_name(issue)
    repo_path = settings.target_repo_path

    if not settings.dry_run:
        log.info("%s: transitioning To Do → In Progress", issue.key)
        await tracker.transition_issue(issue.key, settings.jira_status_in_progress)
    else:
        log.info("[DRY RUN] Would transition %s To Do → In Progress", issue.key)

    if settings.dry_run:
        log.info("[DRY RUN] Would create worktree for branch %s", branch)
        working_dir = repo_path
    else:
        working_dir = await ensure_worktree(branch, repo_path)

    prompt = render_prompt(
        "build_feature.md.j2",
        issue_key=issue.key,
        title=issue.title,
        description=issue.description,
    )

    exit_code, output = await run_tool(
        prompt=prompt,
        working_dir=working_dir,
        tool=settings.tool,
        dry_run=settings.dry_run,
    )

    if exit_code != 0:
        log.warning("%s: tool failed (exit=%d), skipping push", issue.key, exit_code)
        if not settings.dry_run:
            await cleanup_worktree(branch, repo_path)
        return

    # Post the plan file as a Jira comment (if it was created by the AI)
    plan_path = Path(working_dir) / "tasks" / f"plan-{issue.key}.md"
    if not settings.dry_run and plan_path.exists():
        plan_content = plan_path.read_text().strip()
        if plan_content:
            await tracker.add_comment(issue.key, plan_content)
            log.info("%s: posted implementation plan as Jira comment", issue.key)
    elif settings.dry_run:
        log.info("[DRY RUN] Would post plan to Jira for %s", issue.key)

    if settings.dry_run:
        log.info("[DRY RUN] Would push branch %s and create PR", branch)
        return

    await github.push_branch(branch)

    pr_number = await github.find_pr_for_branch(branch)
    if not pr_number:
        await github.create_pr(
            title=f"{issue.key}: {issue.title}",
            body=f"Implements {issue.key}\n\nGenerated by CodeHephaestus.",
            branch=branch,
            draft=True,
        )

    sha_after = await get_current_sha(working_dir)
    loop_prevention.mark_sha_processed(sha_after)
    await cleanup_worktree(branch, repo_path)


async def _handle_review_feedback(
    work: WorkItem,
    *,
    settings: Settings,
    tracker: TaskTracker,
    github: GitHubClient,
    loop_prevention: LoopPrevention,
) -> None:
    """Handle review feedback: address comments, push changes, post summary on PR."""
    issue = work.issue
    branch = tracker.get_issue_branch_name(issue)
    repo_path = settings.target_repo_path

    # If ticket is In Review, transition back to In Progress
    if issue.status == settings.jira_status_in_review:
        if not settings.dry_run:
            log.info("%s: transitioning In Review → In Progress", issue.key)
            await tracker.transition_issue(issue.key, settings.jira_status_in_progress)
        else:
            log.info("[DRY RUN] Would transition %s In Review → In Progress", issue.key)

    if settings.dry_run:
        log.info("[DRY RUN] Would create worktree for branch %s", branch)
        working_dir = repo_path
    else:
        working_dir = await ensure_worktree(branch, repo_path)

    comments = work.context["comments"]

    prompt = render_prompt(
        "answer_comments.md.j2",
        issue_key=issue.key,
        title=issue.title,
        description=issue.description,
        comments=comments,
    )

    exit_code, output = await run_tool(
        prompt=prompt,
        working_dir=working_dir,
        tool=settings.tool,
        dry_run=settings.dry_run,
    )

    if exit_code != 0:
        log.warning("%s: tool failed (exit=%d), skipping push", issue.key, exit_code)
        if not settings.dry_run:
            await cleanup_worktree(branch, repo_path)
        return

    if settings.dry_run:
        log.info("[DRY RUN] Would push changes and post PR comment for %s", branch)
        return

    await github.push_branch(branch)

    # Post summary comment on PR listing what feedback was addressed
    pr_number = await github.find_pr_for_branch(branch)
    if pr_number:
        summary_lines = ["Addressed the following review feedback:"]
        for c in comments:
            summary_lines.append(f"- **{c['author']}** ({c['source']}): {c['body']}")
        await github.post_pr_comment(pr_number, "\n".join(summary_lines))

    sha_after = await get_current_sha(working_dir)
    loop_prevention.mark_sha_processed(sha_after)
    await cleanup_worktree(branch, repo_path)


async def _handle_ci_failure(
    work: WorkItem,
    *,
    settings: Settings,
    tracker: TaskTracker,
    github: GitHubClient,
    loop_prevention: LoopPrevention,
) -> None:
    """Handle CI failure: fix the failing checks, push changes."""
    issue = work.issue
    branch = tracker.get_issue_branch_name(issue)
    repo_path = settings.target_repo_path

    if settings.dry_run:
        log.info("[DRY RUN] Would create worktree for branch %s", branch)
        working_dir = repo_path
    else:
        working_dir = await ensure_worktree(branch, repo_path)

    prompt = render_prompt(
        "fix_ci.md.j2",
        issue_key=issue.key,
        title=issue.title,
        description=issue.description,
        check_output=work.context.get("check_output", ""),
    )

    exit_code, output = await run_tool(
        prompt=prompt,
        working_dir=working_dir,
        tool=settings.tool,
        dry_run=settings.dry_run,
    )

    if exit_code != 0:
        log.warning("%s: tool failed (exit=%d), skipping push", issue.key, exit_code)
        if not settings.dry_run:
            await cleanup_worktree(branch, repo_path)
        return

    if settings.dry_run:
        log.info("[DRY RUN] Would push CI fix for %s", branch)
        return

    await github.push_branch(branch)

    sha_after = await get_current_sha(working_dir)
    loop_prevention.mark_sha_processed(sha_after)
    await cleanup_worktree(branch, repo_path)


async def _handle_work_item(
    work: WorkItem,
    *,
    settings: Settings,
    tracker: TaskTracker,
    github: GitHubClient,
    loop_prevention: LoopPrevention,
) -> None:
    issue = work.issue

    loop_prevention.record_attempt(issue.key)
    loop_prevention.mark_feedback_processed(issue.key)

    handlers = {
        Tier.NEW_ISSUE: _handle_new_issue,
        Tier.REVIEW_FEEDBACK: _handle_review_feedback,
        Tier.CI_FAILURE: _handle_ci_failure,
    }

    handler = handlers.get(work.tier)
    if not handler:
        log.error("Unknown tier: %s", work.tier)
        return

    await handler(
        work,
        settings=settings,
        tracker=tracker,
        github=github,
        loop_prevention=loop_prevention,
    )


async def run_loop(settings: Settings) -> None:
    from codehephaestus.trackers import create_tracker

    tracker = create_tracker(settings)
    github = GitHubClient(settings.target_repo_path)
    loop_prevention = LoopPrevention()
    dispatcher = PriorityDispatcher(tracker, github, settings, loop_prevention)

    await boot(settings, tracker, github)

    iteration = 0
    mode = "infinite mode" if settings.max_iterations == 0 else f"max {settings.max_iterations}"

    while settings.max_iterations == 0 or iteration < settings.max_iterations:
        iteration += 1
        log.info("=== Iteration %d (%s) ===", iteration, mode)

        # Keep main up to date so new branches start from latest
        await update_main(settings.target_repo_path)

        # Housekeeping
        await dispatcher.check_merged_prs()
        await dispatcher.check_ci_passed()

        # Find next work item
        work = await dispatcher.find_next_work_item()

        if work:
            await _handle_work_item(
                work,
                settings=settings,
                tracker=tracker,
                github=github,
                loop_prevention=loop_prevention,
            )
        else:
            log.info("No work found.")

        if settings.max_iterations != 0 and iteration >= settings.max_iterations:
            break

        log.info("Iteration %d complete. Sleeping %ds...", iteration, settings.poll_interval)
        await asyncio.sleep(settings.poll_interval)

    log.info("Loop finished after %d iterations.", iteration)

    if hasattr(tracker, "close"):
        await tracker.close()
